### ISSUE TITLE
generator

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/CraftyComponents#1]
A new page where you can select crafty version and a number of components and their version. The page will then combine the js files (appending the components to crafty) and provide a single download.

See https://groups.google.com/forum/?fromgroups#!topic/craftyjs/JMVYTe3LUPo

**Comment by ahilles107** [comment]
We can name this crafty packages as "distributions" and create some defaults and hosts them directly from site.

**Comment by potomak** [comment]
Interesting idea, see also https://github.com/sgmeyer/generator-crafty.
